=== motiv-labs/motation-spec/v9/schema/single/single-schema-with-ids.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "description": "A schema that validates the structure of a Mutation file",
  "type": "object",
  "required": [
    "systems",
    "definition",
    "contents",
    "audit",
    "key"
  ],
  "properties": {
    "systems": {
      "type": "array",
      "items": {
        "$ref": "#global-system"
      },
      "minItems": 1,
      "uniqueItems": true
    },
    "dependencies": {
      "type": "object",
      "properties": {
        "languages": {
          "type": "array",
          "items": {
            "$ref": "#dep-language"
          },
          "minItems": 1,
          "uniqueItems": true
        },
        "tags": {
          "type": "array",
          "items": {
            "$ref": "#dep-tag"
          },
          "uniqueItems": true
        },
        "categories": {
          "type": "array",
          "items": {
            "$ref": "#dep-category"
          },
          "uniqueItems": true
        },
        "relationships": {
          "type": "array",
          "items": {
            "$ref": "#dep-relationship"
          },
          "uniqueItems": true
        }
      }
    },
    "definition": {
      "type": "object",
      "required": [
        "id",
        "properties",
        "fields"
      ],
      "properties": {
        "id": {
          "type": "array",
          "items": {
            "$ref": "#common-id"
          },
          "minItems": 1,
          "uniqueItems": true
        },
        "properties": {
          "type": "object",
          "$ref": "#def-properties"
        },
        "fields": {
          "type": "array",
          "items": {
            "$ref": "#def-field"
          },
          "minItems": 1,
          "uniqueItems": true
        }
      }
    },
    "contents": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "id",
          "properties",
          "versions"
        ],
        "properties": {
          "id": {
            "type": "array",
            "items": {
              "$ref": "#common-id"
            },
            "uniqueItems": true
          },
          "properties": {
            "type": "object",
            "$ref": "#content-properties"
          },
          "versions": {
            "type": "array",
            "items": {
              "$ref": "#content-version"
            },
            "minItems": 1,
            "uniqueItems": true
          }
        }
      },
      "minItems": 1,
      "uniqueItems": true
    },
    "audit": {
      "type": "array",
      "items": {
        "$ref": "#global-audit"
      },
      "minItems": 1,
      "uniqueItems": true
    },
    "key": {
      "required": [
        "fields"
      ],
      "properties": {
        "fields": {
          "type": "array",
          "items": {
            "$ref": "#key-field"
          },
          "minItems": 1,
          "uniqueItems": true
        }
      }
    }
  },
  "definitions": {
    "id": {
      "$id": "#common-id",
      "required": [
        "value"
      ],
      "properties": {
        "label": {
          "type": "string"
        },
        "value": {
          "type": "string"
        }
      }
    },
    "metadata": {
      "$id": "#common-metadata",
      "properties": {
        "items": {
          "type": "array"
        }
      }
    },
    "system": {
      "$id": "#common-system",
      "properties": {
        "items": {
          "type": "array"
        }
      }
    },
    "properties": {
      "$id": "#def-properties",
      "required": [
        "uniqueName",
        "type"
      ],
      "properties": {
        "uniqueName": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "type": {
          "enum": [
            "Content",
            "Widget",
            "Form",
            "File",
            "Page",
            "Persona"
          ]
        },
        "creationDate": {
          "type": "string"
        },
        "modificationDate": {
          "type": "string"
        },
        "parent": {
          "type": "object",
          "$ref": "#def-parent"
        },
        "metadata": {
          "type": "object",
          "$ref": "#common-metadata"
        },
        "system": {
          "type": "object",
          "$ref": "#common-system"
        }
      }
    },
    "parent": {
      "$id": "#def-parent",
      "properties": {
        "type": {
          "enum": [
            "Site",
            "Folder"
          ]
        },
        "id": {
          "type": "array",
          "items": {
            "$ref": "#common-id"
          },
          "uniqueItems": true
        }
      },
      "required": [
        "type",
        "id"
      ],
      "additionalProperties": false
    },
    "fullMetadata": {
      "$id": "#def-fullMetadata",
      "required": [
        "key",
        "value"
      ],
      "properties": {
        "id": {
          "type": "array",
          "items": {
            "$ref": "#common-id"
          },
          "minItems": 1,
          "uniqueItems": true
        },
        "name": {
          "type": "string"
        },
        "key": {
          "type": "string"
        },
        "value": {
          "type": "string"
        },
        "creationDate": {
          "type": "string"
        },
        "modificationDate": {
          "type": "string"
        }
      }
    },
    "validation": {
      "$id": "#def-validation",
      "properties": {
        "name": {
          "type": "string"
        },
        "required": {
          "type": "boolean"
        },
        "minLength": {
          "type": "number"
        },
        "maxLength": {
          "type": "number"
        },
        "regex": {
          "type": "string"
        }
      }
    },
    "constraint": {
      "$id": "#def-constraint",
      "properties": {
        "unique": {
          "type": "boolean"
        },
        "readOnly": {
          "type": "boolean"
        },
        "fixed": {
          "type": "boolean"
        }
      }
    },
    "display": {
      "$id": "#def-display",
      "properties": {
        "showInList": {
          "type": "boolean"
        },
        "searchable": {
          "type": "boolean"
        },
        "hint": {
          "type": "string"
        }
      }
    },
    "dataType": {
      "$id": "#def-dataType",
      "enum": [
        "String",
        "BigString",
        "Boolean",
        "Int",
        "BigInt",
        "Float",
        "Date",
        "Time",
        "DateTime"
      ]
    },
    "field": {
      "$id": "#def-field",
      "required": [
        "id",
        "properties"
      ],
      "properties": {
        "id": {
          "type": "array",
          "items": {
            "$ref": "#common-id"
          },
          "uniqueItems": true
        },
        "properties": {
          "required": [
            "fieldType",
            "name"
          ],
          "properties": {
            "dataType": {
              "type": "string",
              "$ref": "#def-dataType"
            },
            "fieldType": {
              "enum": [
                "Text",
                "Category",
                "Checkbox",
                "Constant",
                "Custom",
                "Date",
                "Datetime",
                "File",
                "Hidden",
                "Site",
                "Image",
                "KeyValue",
                "Divider",
                "Select",
                "Multiselect",
                "Tab",
                "Radio",
                "Relationship",
                "RelationshipTab",
                "Permission",
                "Tag",
                "Textarea",
                "Binary",
                "Time",
                "WYSIWYG",
                "Row",
                "Column"
              ]
            },
            "validations": {
              "type": "array",
              "items": {
                "$ref": "#def-validation"
              },
              "uniqueItems": true
            },
            "constraints": {
              "type": "array",
              "items": {
                "$ref": "#def-constraint"
              },
              "uniqueItems": true
            },
            "display": {
              "type": "array",
              "items": {
                "$ref": "#def-display"
              },
              "uniqueItems": true
            },
            "system": {
              "type": "object",
              "$ref": "#common-system"
            },
            "metadata": {
              "type": "array",
              "items": {
                "$ref": "#def-fullMetadata"
              },
              "uniqueItems": true
            },
            "uniqueName": {
              "type": "string"
            },
            "order": {
              "type": "integer"
            },
            "description": {
              "type": "string"
            },
            "setUpData": {
              "type": "string"
            },
            "name": {
              "type": "string"
            },
            "defaultValue": {
              "type": "string"
            },
            "creationDate": {
              "type": "string"
            },
            "modificationDate": {
              "type": "string"
            }
          }
        }
      }
    },
    "storage": {
      "$id": "#content-storage",
      "required": [
        "bucket",
        "md5"
      ],
      "properties": {
        "bucket": {
          "type": "string"
        },
        "md5": {
          "type": "string"
        }
      }
    },
    "status": {
      "$id": "#content-status",
      "enum": [
        "Live",
        "Working",
        "Deleted"
      ]
    },
    "content-properties": {
      "$id": "#content-properties",
      "required": [
        "definitionId",
        "name",
        "type",
        "path"
      ],
      "properties": {
        "type": {
          "enum": [
            "Content",
            "Page",
            "Folder"
          ]
        },
        "status": {
          "$ref": "#content-status"
        },
        "languageId": {
          "type": "array",
          "items": {
            "$ref": "#common-id"
          },
          "uniqueItems": true
        },
        "definitionId": {
          "type": "array",
          "items": {
            "$ref": "#common-id"
          },
          "uniqueItems": true
        },
        "name": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "path": {
          "type": "string"
        },
        "site": {
          "type": "string"
        },
        "system": {
          "type": "object",
          "$ref": "#common-system"
        },
        "creationDate": {
          "type": "string"
        },
        "modificationDate": {
          "type": "string"
        }
      }
    },
    "version": {
      "$id": "#content-version",
      "required": [
        "id",
        "properties",
        "fields"
      ],
      "properties": {
        "id": {
          "type": "array",
          "items": {
            "$ref": "#common-id"
          },
          "uniqueItems": true
        },
        "properties": {
          "properties": {
            "status": {
              "$ref": "#content-status"
            },
            "title": {
              "type": "string"
            },
            "order": {
              "type": "integer"
            },
            "metadata": {
              "type": "object",
              "$ref": "#common-metadata"
            },
            "system": {
              "type": "object",
              "$ref": "#common-system"
            },
            "creationDate": {
              "type": "string"
            },
            "modificationDate": {
              "type": "string"
            },
            "modificationUser": {
              "type": "array",
              "items": {
                "$ref": "#common-id"
              },
              "uniqueItems": true
            }
          }
        },
        "fields": {
          "$id": "#content-fields",
          "type": "array",
          "items": {
            "$ref": "#content-field"
          },
          "uniqueItems": true
        }
      }
    },
    "content-field": {
      "$id": "#content-field",
      "required": [
        "id"
      ],
      "properties": {
        "id": {
          "type": "array",
          "items": {
            "$ref": "#common-id"
          },
          "uniqueItems": true
        },
        "value": {
          "type": "string"
        },
        "storage": {
          "type": "object",
          "$ref": "#content-storage"
        }
      }
    },
    "relationship": {
      "$id": "#dep-relationship",
      "required": [
        "id",
        "properties"
      ],
      "properties": {
        "id": {
          "type": "array",
          "items": {
            "$ref": "#common-id"
          },
          "minItems": 1,
          "uniqueItems": true
        },
        "properties": {
          "required": [
            "uniqueName",
            "parentId",
            "childId",
            "cardinality"
          ],
          "properties": {
            "uniqueName": {
              "type": "string"
            },
            "parentId": {
              "type": "array",
              "items": {
                "$ref": "#common-id"
              },
              "minItems": 1,
              "uniqueItems": true
            },
            "parentName": {
              "type": "string"
            },
            "childId": {
              "type": "array",
              "items": {
                "$ref": "#common-id"
              },
              "minItems": 1,
              "uniqueItems": true
            },
            "childName": {
              "type": "string"
            },
            "cardinality": {
              "type": "string"
            },
            "system": {
              "type": "object",
              "$ref": "#common-system"
            }
          },
          "relations": {
            "type": "array",
            "items": {
              "$ref": "#dep-relation"
            },
            "uniqueItems": true
          }
        }
      }
    },
    "relation": {
      "$id": "#dep-relation",
      "required": [
        "parent",
        "child"
      ],
      "properties": {
        "parent": {
          "type": "array",
          "items": {
            "$ref": "#common-id"
          },
          "minItems": 1,
          "uniqueItems": true
        },
        "child": {
          "type": "array",
          "items": {
            "$ref": "#common-id"
          },
          "minItems": 1,
          "uniqueItems": true
        },
        "order": {
          "type": "integer"
        }
      }
    },
    "category": {
      "$id": "#dep-category",
      "required": [
        "id",
        "properties"
      ],
      "properties": {
        "id": {
          "type": "array",
          "items": {
            "$ref": "#common-id"
          },
          "minItems": 1,
          "uniqueItems": true
        },
        "properties": {
          "required": [
            "name"
          ],
          "properties": {
            "name": {
              "type": "string"
            },
            "uniqueName": {
              "type": "string"
            },
            "order": {
              "type": "integer"
            },
            "system": {
              "type": "object",
              "$ref": "#common-system"
            },
            "modificationDate": {
              "type": "string"
            }
          }
        },
        "children": {
          "type": "array",
          "items": {
            "$ref": "#dep-category"
          },
          "uniqueItems": true
        }
      }
    },
    "tag": {
      "$id": "#dep-tag",
      "required": [
        "id",
        "name"
      ],
      "properties": {
        "id": {
          "type": "array",
          "items": {
            "$ref": "#common-id"
          },
          "minItems": 1,
          "uniqueItems": true
        },
        "name": {
          "type": "string"
        },
        "site": {
          "type": "string"
        },
        "system": {
          "type": "object",
          "$ref": "#common-system"
        },
        "modificationUser": {
          "type": "array",
          "items": {
            "$ref": "#common-id"
          },
          "uniqueItems": true
        },
        "modificationDate": {
          "type": "string"
        }
      }
    },
    "language": {
      "$id": "#dep-language",
      "required": [
        "id"
      ],
      "properties": {
        "id": {
          "type": "array",
          "items": {
            "$ref": "#common-id"
          },
          "minItems": 1,
          "uniqueItems": true
        },
        "language": {
          "type": "string"
        },
        "languageCode": {
          "type": "string"
        },
        "country": {
          "type": "string"
        },
        "countryCode": {
          "type": "string"
        }
      }
    },
    "global-system": {
      "$id": "#global-system",
      "required": [
        "name",
        "date"
      ],
      "properties": {
        "name": {
          "type": "string"
        },
        "version": {
          "type": "string"
        },
        "date": {
          "type": "string"
        }
      },
      "additionalProperties": false
    },
    "global-audit": {
      "$id": "#global-audit",
      "required": [
        "date"
      ],
      "properties": {
        "user": {
          "type": "object",
          "$ref": "#global-user"
        },
        "date": {
          "type": "string"
        }
      }
    },
    "global-user": {
      "$id": "#global-user",
      "properties": {
        "id": {
          "type": "object",
          "$ref": "#common-id"
        },
        "name": {
          "type": "string"
        },
        "email": {
          "type": "string"
        },
        "username": {
          "type": "string"
        }
      }
    },
    "key-field": {
      "$id": "#key-field",
      "required": [
        "name",
        "id"
      ],
      "properties": {
        "name": {
          "type": "string"
        },
        "id": {
          "type": "array",
          "items": {
            "$ref": "#common-id"
          },
          "minItems": 1,
          "uniqueItems": true
        }
      }
    }
  }
}

=== motiv-labs/motation-spec/v9/examples/full/example-file.json
{
  "systems":[
    {
      "name":"dotCMS 5.2.7",
      "date":"2021-07-14 18:53:09.18862463 +0000 UTC m=+641.919624176"
    }
  ],
  "dependencies":{
  },
  "definition":{
    "id":[
      {
        "value":"9727c4e6-786c-4b20-b581-0a3ea1bb38d4"
      }
    ],
    "properties":{
      "type":"File",
      "uniqueName":"Image",
      "name":"Image",
      "parent":{
        "type":"Site",
        "id":[
          {
            "value":"8a7d5e23-da1e-420a-b4f0-471e7da8ea2d"
          }
        ]
      },
      "system":{
        "default_structure":"false",
        "fixed":"false",
        "folder":"SYSTEM_FOLDER",
        "system":"false"
      },
      "modificationDate":"2021-07-14 18:43:48 +0000 UTC"
    },
    "fields":[
      {
        "id":[
          {
            "value":"80a8ba12-e69d-4f23-8a97-40c3cb136927"
          }
        ],
        "properties":{
          "dataType":"String",
          "fieldType":"Site",
          "validations":[
            {
              "required":true
            }
          ],
          "constraints":[
            {
              "unique":false
            },
            {
              "readOnly":false
            },
            {
              "fixed":true
            }
          ],
          "display":[
            {
              "searchable":true
            },
            {
              "showInList":false
            }
          ],
          "system":{
            "field_contentlet":"system_field",
            "indexed":"true"
          },
          "order":0,
          "uniqueName":"hostFolder",
          "name":"Site or Folder",
          "modificationDate":"2021-07-14 18:43:47 +0000 UTC"
        }
      },
      {
        "id":[
          {
            "value":"8c6ad292-547e-4d27-9552-c9ad49ad0bca"
          }
        ],
        "properties":{
          "dataType":"String",
          "fieldType":"Binary",
          "validations":[
            {
              "required":true
            }
          ],
          "constraints":[
            {
              "unique":false
            },
            {
              "readOnly":false
            },
            {
              "fixed":true
            }
          ],
          "display":[
            {
              "searchable":true
            },
            {
              "showInList":false
            }
          ],
          "system":{
            "field_contentlet":"system_field",
            "indexed":"true"
          },
          "order":1,
          "uniqueName":"fileAsset",
          "name":"File Asset",
          "modificationDate":"2021-07-14 18:43:47 +0000 UTC"
        }
      },
      {
        "id":[
          {
            "value":"6a582bf1-bfee-4964-b903-a34699f231a9"
          }
        ],
        "properties":{
          "dataType":"String",
          "fieldType":"Text",
          "validations":[
            {
              "required":true
            }
          ],
          "constraints":[
            {
              "unique":false
            },
            {
              "readOnly":false
            },
            {
              "fixed":true
            }
          ],
          "display":[
            {
              "searchable":true
            },
            {
              "showInList":false
            }
          ],
          "system":{
            "field_contentlet":"text1",
            "indexed":"true"
          },
          "order":2,
          "uniqueName":"title",
          "name":"Title",
          "modificationDate":"2021-07-14 18:43:48 +0000 UTC"
        }
      },
      {
        "id":[
          {
            "value":"6a859c54-11fb-4be7-bb41-ec07e5f56f3d"
          }
        ],
        "properties":{
          "dataType":"String",
          "fieldType":"Text",
          "validations":[
            {
              "required":false
            }
          ],
          "constraints":[
            {
              "unique":false
            },
            {
              "readOnly":false
            },
            {
              "fixed":true
            }
          ],
          "display":[
            {
              "searchable":true
            },
            {
              "showInList":true
            }
          ],
          "system":{
            "field_contentlet":"text2",
            "indexed":"true"
          },
          "order":3,
          "uniqueName":"fileName",
          "name":"File Name",
          "modificationDate":"2021-07-14 18:43:48 +0000 UTC"
        }
      },
      {
        "id":[
          {
            "value":"8da9a418-87d0-4aee-a401-ae7be926715e"
          }
        ],
        "properties":{
          "dataType":"String",
          "fieldType":"Tab",
          "validations":[
            {
              "required":false
            }
          ],
          "constraints":[
            {
              "unique":false
            },
            {
              "readOnly":false
            },
            {
              "fixed":false
            }
          ],
          "display":[
            {
              "searchable":false
            },
            {
              "showInList":false
            }
          ],
          "system":{
            "field_contentlet":"system_field",
            "indexed":"false"
          },
          "order":4,
          "uniqueName":"metadataTab",
          "name":"Metadata",
          "modificationDate":"2021-07-14 18:43:48 +0000 UTC"
        }
      },
      {
        "id":[
          {
            "value":"64e7ad1d-6539-4721-be7d-0b6027be5259"
          }
        ],
        "properties":{
          "dataType":"BigString",
          "fieldType":"KeyValue",
          "validations":[
            {
              "required":false
            }
          ],
          "constraints":[
            {
              "unique":false
            },
            {
              "readOnly":true
            },
            {
              "fixed":true
            }
          ],
          "display":[
            {
              "searchable":true
            },
            {
              "showInList":false
            }
          ],
          "system":{
            "field_contentlet":"text_area1",
            "indexed":"true"
          },
          "order":5,
          "uniqueName":"metaData",
          "name":"Metadata",
          "modificationDate":"2021-07-14 18:43:48 +0000 UTC"
        }
      },
      {
        "id":[
          {
            "value":"288e1d7a-1fad-407b-859c-384ba312af27"
          }
        ],
        "properties":{
          "dataType":"String",
          "fieldType":"Checkbox",
          "validations":[
            {
              "required":false
            }
          ],
          "constraints":[
            {
              "unique":false
            },
            {
              "readOnly":false
            },
            {
              "fixed":true
            }
          ],
          "display":[
            {
              "searchable":false
            },
            {
              "showInList":false
            }
          ],
          "system":{
            "field_contentlet":"text3",
            "indexed":"true"
          },
          "order":6,
          "uniqueName":"showOnMenu",
          "setUpData":"|true",
          "name":"Show on Menu",
          "defaultValue":"false",
          "modificationDate":"2021-07-14 18:43:48 +0000 UTC"
        }
      },
      {
        "id":[
          {
            "value":"0a50eb4b-2073-4ae2-82fc-ab2a046d7e91"
          }
        ],
        "properties":{
          "dataType":"Int",
          "fieldType":"Text",
          "validations":[
            {
              "required":false
            }
          ],
          "constraints":[
            {
              "unique":false
            },
            {
              "readOnly":false
            },
            {
              "fixed":true
            }
          ],
          "display":[
            {
              "searchable":true
            },
            {
              "showInList":false
            }
          ],
          "system":{
            "field_contentlet":"integer1",
            "indexed":"true"
          },
          "order":7,
          "uniqueName":"sortOrder",
          "name":"Sort Order",
          "defaultValue":"0",
          "modificationDate":"2021-07-14 18:43:48 +0000 UTC"
        }
      },
      {
        "id":[
          {
            "value":"512503af-cb80-46ce-b12e-26135e7ea3aa"
          }
        ],
        "properties":{
          "dataType":"BigString",
          "fieldType":"Textarea",
          "validations":[
            {
              "required":false
            }
          ],
          "constraints":[
            {
              "unique":false
            },
            {
              "readOnly":false
            },
            {
              "fixed":true
            }
          ],
          "display":[
            {
              "searchable":false
            },
            {
              "showInList":false
            }
          ],
          "system":{
            "field_contentlet":"text_area2",
            "indexed":"true"
          },
          "order":8,
          "uniqueName":"description",
          "name":"Description",
          "modificationDate":"2021-07-14 18:43:48 +0000 UTC"
        }
      }
    ]
  },
  "contents":[
    {
      "id":[
        {
          "value":"ed88ee7d-5edb-4918-9891-43d91697c261"
        }
      ],
      "properties":{
        "type":"Content",
        "status":"Live",
        "languageId":[
          {
            "value":"1"
          }
        ],
        "definitionId":[
          {
            "value":"9727c4e6-786c-4b20-b581-0a3ea1bb38d4"
          }
        ],
        "name":"img1.jpg",
        "path":"/Documents/",
        "site":"b91f2b4b-ac64-429e-8a58-5c3f8484a600",
        "system":{
        }
      },
      "versions":[
        {
          "id":[
            {
