=== motiv-labs/motation-spec/schema/full-generic-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "description": "A schema that validates the structure of a Motation file",
  "type": "object",
  "required": [
    "systems",
    "contents",
    "audit",
    "key"
  ],
  "properties": {
    "systems": {
      "type": "array",
      "items": {
        "$ref": "#global-system"
      },
      "minItems": 1,
      "uniqueItems": true
    },
    "dependencies": {
      "type": "object",
      "$ref": "dependencies-schema.json"
    },
    "definition": {
      "type": "object",
      "$ref": "definition-field-schema.json"
    },
    "contents": {
      "type": "array",
      "items": {
        "$ref": "content-schema.json"
      },
      "minItems": 1,
      "uniqueItems": true
    },
    "audit": {
      "type": "array",
      "items": {
        "$ref": "#global-audit"
      },
      "minItems": 1,
      "uniqueItems": true
    },
    "key": {
      "required": [
        "fields"
      ],
      "properties": {
        "fields": {
          "type": "array",
          "items": {
            "$ref": "#key-field"
          },
          "minItems": 1,
          "uniqueItems": true
        }
      }
    }
  },
  "definitions": {
    "system": {
      "$id": "#global-system",
      "required": [
        "name",
        "date"
      ],
      "properties": {
        "name": {
          "type": "string"
        },
        "version": {
          "type": "string"
        },
        "date": {
          "type": "string"
        }
      },
      "additionalProperties": false
    },
    "audit": {
      "$id": "#global-audit",
      "required": [
        "date"
      ],
      "properties": {
        "user": {
          "type": "object",
          "$ref": "#global-user"
        },
        "date": {
          "type": "string"
        }
      }
    },
    "user": {
      "$id": "#global-user",
      "properties": {
        "id": {
          "type": "object",
          "$ref": "common-schema.json#/definitions/id"
        },
        "name": {
          "type": "string"
        },
        "email": {
          "type": "string"
        },
        "username": {
          "type": "string"
        }
      }
    },
    "key-field": {
      "$id": "#key-field",
      "required": [
        "name",
        "id"
      ],
      "properties": {
        "name": {
          "type": "string"
        },
        "id": {
          "type": "array",
          "items": {
            "$ref": "common-schema.json#/definitions/id"
          },
          "minItems": 1,
          "uniqueItems": true
        }
      }
    }
  }
}

=== motiv-labs/motation-spec/v9/examples/motationObjects/example-domain.json
{
  "systems":[
    {
      "name":"dotCMS 5.2.7",
      "date":"2021-07-14 18:53:09.139091659 +0000 UTC m=+641.870090928"
    }
  ],
  "dependencies":{
  },
  "definition": {
    "reference": "domain-definition-motation-id"
  },
  "contents":[
    {
      "id":[
        {
          "value":"b91f2b4b-ac64-429e-8a58-5c3f8484a600"
        }
      ],
      "properties":{
        "type":"Content",
        "status":"Live",
        "languageId":[
          {
            "value":"1"
          }
        ],
        "definitionId":[
          {
            "value":"855a2d72-f2f3-4169-8b04-ac5157c4380c"
          }
        ],
        "name":"content.919ec2be-4eb4-4a25-8156-4c086af4ae03",
        "path":"/",
        "site":"SYSTEM_HOST",
        "system":{
        }
      },
      "versions":[
        {
          "id":[
            {
              "value":"da3680a3-f2fb-4737-9173-81e632b83878"
            }
          ],
          "properties":{
            "status":"Live",
            "title":"site1",
            "order":0,
            "modificationDate":"2020-08-18 23:27:32.121 +0000 UTC",
            "modificationUser":[
              {
                "value":"dotcms.org.1"
              }
            ],
            "system":{
              "friendly_name":"site1",
              "last_review":"2020-08-18 23:27:32.094 +0000 UTC",
              "show_on_menu":"false"
            }
          },
          "fields":[
            {
              "id":[
                {
                  "value":"ec8cc36f-6058-4ab5-9bfb-fc36ab011ee5"
                }
              ],
              "value":"site1"
            },
            {
              "id":[
                {
                  "value":"cf5d08aa-7ff0-4fc8-a6ac-5a36e82cd741"
                }
              ],
              "value":"b91f2b4b-ac64-429e-8a58-5c3f8484a600"
            },
            {
              "id":[
                {
                  "value":"c4628fad-9122-404a-8248-faaac4e6c29f"
                }
              ],
              "value":"false"
            },
            {
              "id":[
                {
                  "value":"a0712c61-06ec-4019-a148-21d53fe05f92"
                }
              ],
              "value":"false"
            },
            {
              "id":[
                {
                  "value":"2f00a11d-f64c-4f8f-8126-238cc01fbf96"
                }
              ],
              "value":"false"
            }
          ]
        }
      ]
    }
  ],
  "audit":[
    {
      "date":"2021-07-14 18:53:09.139120783 +0000 UTC m=+641.870120051"
    }
  ],
  "key":{
    "fields":[
      {
        "name":"addThis",
        "id":[
          {
            "value":"4242af9d-2cc9-440f-a136-c92f1fe0e65a"
          }
        ]
      },
      {
        "name":"aliases",
        "id":[
          {
            "value":"01f23a87-9859-4860-8368-f70a6ba9687f"
          }
        ]
      },
      {
        "name":"description",
        "id":[
          {
            "value":"04b1cdea-6c48-4a1b-bf47-6edfd5091246"
          }
        ]
      },
      {
        "name":"embeddedDashboard",
        "id":[
          {
            "value":"8f62657b-8915-489c-820e-12e8e272f1c1"
          }
        ]
      },
      {
        "name":"googleAnalytics",
        "id":[
          {
            "value":"02d02031-ef53-43f2-9845-6a2a85538072"
          }
        ]
      },
      {
        "name":"googleMap",
        "id":[
          {
            "value":"f41dcc3c-36ce-4ea5-a621-23011936c418"
          }
        ]
      },
      {
        "name":"hostName",
        "id":[
          {
            "value":"ec8cc36f-6058-4ab5-9bfb-fc36ab011ee5"
          }
        ]
      },
      {
        "name":"hostThumbnail",
        "id":[
          {
            "value":"8377586d-ac40-43b9-81ce-55b64f24433b"
          }
        ]
      },
      {
        "name":"isDefault",
        "id":[
          {
            "value":"c4628fad-9122-404a-8248-faaac4e6c29f"
          }
        ]
      },
      {
        "name":"isSystemHost",
        "id":[
          {
            "value":"a0712c61-06ec-4019-a148-21d53fe05f92"
          }
        ]
      },
      {
        "name":"keywords",
        "id":[
          {
            "value":"bca1a66b-4ab0-44aa-b73c-502390d4b4f1"
          }
        ]
      },
      {
        "name":"proxyEditModeUrl",
        "id":[
          {
            "value":"f7f559fd-7100-45f5-b4e9-131a9d63984c"
          }
        ]
      },
      {
        "name":"runDashboard",
        "id":[
          {
            "value":"2f00a11d-f64c-4f8f-8126-238cc01fbf96"
          }
        ]
      },
      {
        "name":"tagStorage",
        "id":[
          {
            "value":"cf5d08aa-7ff0-4fc8-a6ac-5a36e82cd741"
          }
        ]
      }
    ]
  }
}
