=== motiv-labs/motation-spec/schema/full-language-definition-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "description": "A schema that validates the structure of Definition Motation Object Field",
  "$id": "full-language-definition-schema.json",
  "allOf": [
    {
      "$ref": "full-definition-schema.json"
    }
  ],
  "type": "object",
  "required": [
    "systems",
    "contents",
    "audit",
    "key"
  ],
  "properties": {
    "systems": {
      "type": "array",
      "items": {
        "$ref": "#global-system"
      },
      "minItems": 1,
      "uniqueItems": true
    },
    "definition": {
      "type": "object",
      "allOf": [
        {
          "properties": {
            "fields": {
              "type": "array",
              "items": {
                "allOf": [
                  {
                    "$ref": "definition-field-schema.json#/definitions/field"
                  }
                ]
              },
              "allOf": [
                {
                  "contains": {
                    "properties": {
                      "properties": {
                        "type": "object",
                        "properties": {
                          "fieldType": {
                            "type": "string",
                            "const": "DefinitionFieldProperties"
                          },
                          "name": {
                            "type": "string",
                            "const": "language"
                          }
                        }
                      }
                    }
                  }
                },
                {
                  "contains": {
                    "properties": {
                      "properties": {
                        "type": "object",
                        "properties": {
                          "fieldType": {
                            "type": "string",
                            "const": "DefinitionFieldProperties"
                          },
                          "name": {
                            "type": "string",
                            "const": "languageCode"
                          }
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      ],
      "properties": {
        "fields": {
          "type": "array",
          "items": {
            "$ref": "definition-field-schema.json#/definitions/field"
          },
          "minItems": 2
        }
      }
    },
    "contents": {
      "type": "array",
      "items": {
        "allOf": [
          {
            "$ref": "definition-content-schema.json"
          },
          {
            "$ref": "#content-field"
          }
        ]
      },
      "minItems": 1,
      "uniqueItems": true
    },
    "audit": {
      "type": "array",
      "items": {
        "$ref": "#global-audit"
      },
      "minItems": 1,
      "uniqueItems": true
    },
    "key": {
      "required": [
        "fields"
      ],
      "properties": {
        "fields": {
          "type": "array",
          "items": {
            "$ref": "#key-field"
          },
          "allOf": [
            {
              "contains": {
                "properties": {
                  "name": {
                    "type": "string",
                    "const": "definitionType"
                  }
                }
              }
            },
            {
              "contains": {
                "properties": {
                  "name": {
                    "type": "string",
                    "const": "definitionUniqueName"
                  }
                }
              }
            }
          ],
          "minItems": 4,
          "uniqueItems": true
        }
      }
    }
  },
  "definitions": {
    "content-field": {
      "$id": "#content-field",
      "properties": {
        "versions": {
          "type": "array",
          "items": {
            "properties": {
              "id": {
                "type": "array"
              },
              "fields": {
                "type": "array",
                "minItems": 4
              }
            }
          }
        }
      }
    },
    "system": {
      "$id": "#global-system",
      "required": [
        "name",
        "date"
      ],
      "properties": {
        "name": {
          "type": "string"
        },
        "version": {
          "type": "string"
        },
        "date": {
          "type": "string"
        }
      },
      "additionalProperties": false
    },
    "audit": {
      "$id": "#global-audit",
      "required": [
        "date"
      ],
      "properties": {
        "user": {
          "type": "object",
          "$ref": "#global-user"
        },
        "date": {
          "type": "string"
        }
      }
    },
    "user": {
      "$id": "#global-user",
      "properties": {
        "id": {
          "type": "object",
          "$ref": "common-schema.json#/definitions/id"
        },
        "name": {
          "type": "string"
        },
        "email": {
          "type": "string"
        },
        "username": {
          "type": "string"
        }
      }
    },
    "key-field": {
      "$id": "#key-field",
      "required": [
        "name",
        "id"
      ],
      "properties": {
        "name": {
          "type": "string"
        },
        "id": {
          "type": "array",
          "items": {
            "$ref": "common-schema.json#/definitions/id"
          },
          "minItems": 1,
          "uniqueItems": true
        }
      }
    }
  }
}

=== motiv-labs/motation-spec/v9/examples/full/example-github-file.json
{
  "systems":[
    {
      "name":"gitHub",
      "date":"2021-07-15 13:06:26.684361148 +0000 UTC m=+307.513383986"
    }
  ],
  "definition":{
    "id":[
      {
        "value":"01FAN4D1QWY4E4XGGVC4TWM954"
      }
    ],
    "properties":{
      "type":"File",
      "uniqueName":"GitHub",
      "name":"GitHub",
      "description":"Content type for GitHub files",
      "system":{
        "after":"c71ffdf6e97d6edcf72ce80bdffe541a7391d820",
        "before":"5c6bd7d8affc3940ffbaf62a353ae5df618176a6",
        "ref":"refs/heads/master",
        "repository":{
          "default_branch":"master",
          "description":null,
          "full_name":"motiv-labs/itest-data",
          "git_url":"git://github.com/motiv-labs/itest-data.git",
          "html_url":"https://github.com/motiv-labs/itest-data",
          "id":281466574,
          "master_branch":"master",
          "name":"itest-data",
          "node_id":"MDEwOlJlcG9zaXRvcnkyODE0NjY1NzQ=",
          "private":false,
          "ssh_url":"git@github.com:motiv-labs/itest-data.git"
        }
      }
    },
    "fields":[
      {
        "id":[
          {
            "value":"01FAN4D1QWHA4ZJ0PWQDPWCY4N"
          }
        ],
        "properties":{
          "dataType":"String",
          "fieldType":"Text",
          "validations":[
            {
              "required":true
            }
          ],
          "display":[
            {
              "searchable":true
            },
            {
              "showInList":true
            }
          ],
          "order":1,
          "uniqueName":"Name",
          "name":"Name"
        }
      },
      {
        "id":[
          {
            "value":"01FAN4D1QWEQGGKWSJ79V5QPVA"
          }
        ],
        "properties":{
          "dataType":"String",
          "fieldType":"Binary",
          "validations":[
            {
              "required":true
            }
          ],
          "display":[
            {
              "searchable":false
            },
            {
              "showInList":false
            }
          ],
          "order":2,
          "uniqueName":"File",
          "name":"File"
        }
      },
      {
        "id":[
          {
            "value":"01FAN4D1QWTWEZH56G9QAEWFJJ"
          }
        ],
        "properties":{
          "dataType":"BigString",
          "fieldType":"Textarea",
          "validations":[
            {
              "required":false
            }
          ],
          "display":[
            {
              "searchable":false
            },
            {
              "showInList":false
            }
          ],
          "order":3,
          "uniqueName":"Description",
          "name":"Description"
        }
      }
    ]
  },
  "contents":[
    {
      "id":[
        {
          "value":"01FAN4D1QWR09ZV9MKC70KD447"
        }
      ],
      "properties":{
        "type":"Content",
        "status":"Live",
        "definitionId":[
          {
            "value":"01FAN4D1QWY4E4XGGVC4TWM954"
          }
        ],
        "name":"pokerap",
        "path":"dont-change/",
        "system":{
          "compare":"https://github.com/motiv-labs/itest-data/compare/5c6bd7d8affc...c71ffdf6e97d"
        }
      },
      "versions":[
        {
          "id":[
            {
              "value":"c71ffdf6e97d6edcf72ce80bdffe541a7391d820"
            }
          ],
          "properties":{
            "status":"Live",
            "title":"pokerap",
            "modificationDate":"2020-07-22 09:11:20 -0400 -0400",
            "system":{
              "message":"Add files via upload",
              "sha":null,
              "tree_id":"344e3679cb40fd9c1827151cb07b91c0b3b42c4c",
              "url":"https://github.com/motiv-labs/itest-data/commit/c71ffdf6e97d6edcf72ce80bdffe541a7391d820"
            }
          },
          "fields":[
            {
              "id":[
                {
                  "value":"01FAN4D1QWEQGGKWSJ79V5QPVA"
                }
              ],
              "storage":{
                "bucket":"0e5bf526-4177-4b85-9e4f-3f64a083db5a",
                "md5":"39958aaf7004a6f99f86d958a0365d11",
                "filePath":"dont-change/",
                "fileName":"pokerap"
              }
            },
            {
              "id":[
                {
                  "value":"01FAN4D1QWHA4ZJ0PWQDPWCY4N"
                }
              ],
              "value":"pokerap"
            },
            {
              "id":[
                {
                  "value":"01FAN4D1QWTWEZH56G9QAEWFJJ"
                }
              ],
              "value":"Add files via upload"
            }
          ]
        }
      ]
    }
  ],
  "audit":[
    {
      "date":"2021-07-15 13:06:26.684393793 +0000 UTC m=+307.513416626",
      "user":{
        "name":"tuxranger",
        "email":"11413392+tuxranger@users.noreply.github.com"
      }
    }
  ],
  "key":{
    "fields":[
      {
        "name":"File",
        "id":[
          {
            "value":"01FAN4D1QWEQGGKWSJ79V5QPVA"
          }
        ]
      }
    ]
  }
}
